# Generated by Django 3.2.6 on 2021-08-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('R', 'Rascunho'), ('P', 'Publicado')], default='R', max_length=1),
        ),
    ]
